### ISSUE TITLE
The readme should include steps to install the tool

### ISSUE THREAD

**Issue by dkaplan-pivotal** [tests-always-included/mo#11]
Not sure how to install this correctly.  Wish it were in `apt-get`.  We've been doing this:

```
dst="${env.HOME}/bin/mo"

if [ ! -x "\$dst" ]; then
  curl -sSo "\$dst" https://raw.githubusercontent.com/tests-always-included/mo/master/mo
  chmod +x "\$dst"
fi
```

**Comment by fidian** [comment]
That works well.  I suppose it depends on whether you want this to be installed locally (which may also involve modifying your PATH environment variable) or globally (where you need root privileges).

I'll add some words to the README because this is a very good point and I don't have that topic covered.

**Comment by fidian** [comment]
I should have not said "this closes #11" because I would like for you to double check that the wording is sufficient and the instructions are clear.  What do you think of the commit I just added?

**Comment by dkaplan-pivotal** [comment]
I don't understand that last section, but that's probably my ignorance of bash scripting.  The other sections make sense to me.  Thanks for the quick turn around time.

**Comment by fidian** [comment]
That last bit is for others who write Bash scripts and they want to exercise the full power of `mo`, complete with iterating across arrays and calling functions.  Not a typical use case.

I'm glad the docs work for you.  Closing the issue.
