### ISSUE TITLE
function call from placeholder

### ISSUE THREAD

**Issue by drslump** [tests-always-included/mo#18]
Let me first say it's a great project!

I was wondering if allowing to use functions from a plain placeholder could be included. Similarly to how it works on [Handlebars' helpers](http://handlebarsjs.com/expressions.html#helpers).

    Hello {{my-upper-fn USER}}!

would replace it with the result of calling `my-upper-fn "$USER"`. The parsing would be something along the lines of:

 - Is there at least a space in the middle of the expression?
 - Is the first token a function?
 - for tokens[1:] resolve their values (allow chained function calls?, allow quoted literals?)
 - call the function passing as arguments the collected values

right now an alternative is possible with:

    Hello {{#my-upper-fn}{{USER}}{{/my-upper-fn}}

but it's verbose and requires expanding the value from the function.

thanks!

**Comment by fidian** [comment]
*Mostly writing notes and thinking out the implementation.*

`{{functionName}}` syntax is already allowed, so there is a precedent for this. What you're asking to do is to have the ability to pass arguments.

Argument processing is going to greatly step up the complexity of the parser. Allowing quoted strings seems like a wonderful thing to do, but then I have to start parsing strings and handling escaped characters. It's a non-trivial task since you have to allow for quoting the braces, handling quotes within quotes, watching out for quoted backslashes before the end of a string, etc. This is going to take a bit of thought and some very thorough tests.

Are you (or is anyone) willing to help make extremely painful scenarios to parse in an attempt to find and prevent bugs before this feature is released?

Eval is simply not an option because I believe that goes against the idea of Mustache. It should be safe for any content to be in a template and have not not accidentally delete files or install rootkits. So far eval was not mentioned in the ticket, and that's excellent. I just wanted to make sure that it didn't crop up.

I'm not yet considering the difficulties of implementing the other features that Handlebars has, such as using `~` to destroy whitespace and nested helper calls.

It does look like we could make this happen. Inside the `moShow()` function, the function in the tag is called here:

    CONTENT=$($1 "")

We would need to get the extra arguments passed into `moShow()` from `moParse()` in both the default tag case and where triple braces are used, possibly as `$3` through `$@`.

**Comment by drslump** [comment]
I totally get your point about the difficulty of handling quoted strings properly. Given that this would be an extension over standard Mustache, perhaps the functionality can be reduced to serve the most common use case, a single argument, and let the function author handle the value.

    {{func foo bar baz}}
    syntax sugar for the already supported:
    {{#func}}foo bar baz{{/func}}

Function authors can then decide how to parse the argument, if it should resolve them from the environment, it's a literal string or even using `getopts` for it. I'm actually liking this more than handling multiple arguments, since it would allow the exposed functions to work with either syntax, enabling the template author to use the one that fits best a specific template.

Perhaps adding the possibility to nest placeholders is simple enough, then it would be trivial to support chaining which would be a common scenario (on my use cases at least) and offer full symmetry with the block syntax:

    {{base64 {{upper {{env BAR}} }} }}

> 💅  trimming the passed values would be golden but that's easy enough to handle inside the functions themselves

**Comment by fidian** [comment]
I believe this finally gets you what you want.

    {{functionName arg1 arg2 "argument three goes here"}}

The `arg1 arg2 "argument three goes here"` bit is simply passed to an `eval`, so be super cautious about using `argument ; rm -rf /` in your template by accident. I've also added a flag that will enable this behavior. It's not enabled by default because it is so risky.

If this isn't what you wanted, comment, reopen, or log a new issue.
