### ISSUE TITLE
Shorter option for --fail-not-set like -n?

### ISSUE THREAD

**Issue by zoobab** [tests-always-included/mo#25]
Hi,

Would it be possible to have a shorter option like "-n" or "-f" instead of "--fail-not-set"?

The other question is whether "--fail-not-set" should not be the default...

Thanks for the tool, I am using j2cli to do the same job atm...

**Comment by fidian** [comment]
I chose `-u` to mirror Bash's flag for producing an error when accessing an undefined variable. Short versions of the other options were added as well, but they must still be separated on the command line.

    # Incorrect
    mo -eusSOURCE_ME TEMPLATE

    # Correct
    mo -e -u -s=SOURCE_ME TEMPLATE

Does that do what you need?

The reason `--fail-not-set` is not the default is because that's part of the mustache spec. I normally am a pretty strict person when it comes to programming, but the spec says that undefined variables are treated as empty strings, so I adhere to that prescribed behavior.

**Comment by fidian** [comment]
Closing for now. Reopen if this is not what you want.
