### ISSUE TITLE
Set a counter in a mustache iteration?

### ISSUE THREAD

**Issue by sc0ttj** [tests-always-included/mo#26]
## The problem:
Using the following template, I cannot produce valid JSON-LD, because there is no easy way (that I can figure out) of NOT appending a comma on the final `items` object:

```
<script id="itemlist-ld" type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "ItemList",
  "itemListElement":
  [
  {{#items}}
    {
      "@type": "ListItem",
      "position": {{items.position}},
      "url": "{{items.url}}"
    },
  {{/items}}
  ]
}
</script>
```

## Solution?

Using a custom function, like here (https://github.com/tests-always-included/mo/blob/master/demo/function-for-advanced-looping), how can I print/append a comma on all _except_ the last iteration?

A real-world example would be very helpful for dummies like me.

**Comment by fidian** [comment]
This looks like you're asking a specific question about mustache templates and not about the command-line `mo` program. If this is wrong, please let me know.

Solution 1: Change the data. Add another property to your input data, then the template can show a comma if that property exists.

    items: [
        { position: "position1", url: "url1", needComma: true },
        { position: "position2", url: "url2", needComma: true },
        { position: "position3", url: "url3" }
    ]

Then your template could use syntax like this.

    {{#needComma}},{{/needComma}}

Solution 2: Using a function. This depends on your library. For `mo`, you define a function in Bash.

    myTestFunction() {
        echo "contents of function here"
    }

How you detect that items passed in are the end of the list is entirely up to you. That changes with each type of library from what I've seen. Given that you are using `{{items.url}}` in your template, I think you have structured data and you might be using JavaScript. If so, you could try to use a closure of some sort.

    // I am just guessing
    mustache.registerFunction("needsComma", item => item !== myGlobalListOfItems[myGlobalListOfItems.length - 1]);

Then your template might be able to use something like this. Again, totally guessing and hoping this helps direct you to the right location.

    {{needsComma "."}}

Closing this issue because I don't believe it deals with `mo`.

**Comment by sc0ttj** [comment]
No, I'm not using JavaScript, I'm using `mo`, obviously.

My questions is not a generic question about mustache - it's more about the lack of multi-dimensional associative arrays in Bash, and how best to workaround it.

I'm asking for a real world example to be added to the `mo` examples` which shows the best way to define (in shell) a custom function that can replaces a standard `{{#FOO}}` iterator with one that can detect if it's the last iteration - using some like `{{#last_itiem}}` used inside the loop..

**Comment by fidian** [comment]
An example was added. Since the point of the exercise was to simply add a comma, I've made it about as basic of an example as is possible. If you really want to work with two dimensional arrays, I suggest you combine the techniques from `function-for-building-json` and `function-for-advanced-looping` together.
