### ISSUE TITLE
Option to fail if a function fail

### ISSUE THREAD

**Issue by felipecassiors** [tests-always-included/mo#38]
It would be awesome to have an option to fail the `mo` execution in case a function fails. Such as `-f` (such as  `curl -f`).

```sh-session
$ echo '{{false}}' | mo -f
mo failed because function 'false' returned a non zero code
$ echo $?
1
```

**Comment by felipecassiors** [comment]
It would be good if we could also enable this per function call, such as:

```
{{ EXIT_ON_ERROR fail }}
```

But I'm not sure about the syntax.

**Comment by fidian** [comment]
I generally agree, but perhaps an alternate solution would be to use a debug version of your function.

    {{ fail }}

If you turn on argument parsing, you could have a wrapper that would write error messages to stderr.

    {{ debug fail }}

and the function would probably look similar to this untested code

    debug() {
        if ! eval "$@"; then
            echo "FAILURE DETECTED: $*" >&2
        fi
    }

**Comment by felipecassiors** [comment]
That's an awesome solution! But I believe it should exist in `mo` itself, so the users wouldn't have to write their own.

Anyway, it's not only useful for debugging scenarios. In my case, I indeed want to stop processing the template, otherwise, 
 the generated file would not match my requirements.

**Comment by fidian** [comment]
I think I understand what you would like, but that really goes against the idea of logic-less templates. I have projects in different languages and they also would benefit from just a little conditional somewhere, but the people watching over the Mustache syntax are totally against the idea, for really good reasons. They would suggest that a variable is set to true/false and the content you want to optionally display should be placed within a tag like this:

    Here is content I always want displayed
    {{#SHOULD_DISPLAY_REST}}
    Additional content I want to display conditionally
    {{/SHOULD_DISPLAY_REST}}

Structuring your program so that all of the necessary information is available before the template is rendered will help you achieve this goal and stay within the ideals of Mustache templating. Once processed, the lines that contain only tags should be eliminated from the result, so you should be left with this

    Here is content I always want displayed

or this

    Here is content I always want displayed
    Additional content I want to display conditionally

depending on the value of `$SHOULD_DISPLAY_REST`.

I hope this helps.

**Comment by felipecassiors** [comment]
So, what if I have something like this:

```bash
function get_version_somehow() {
  echo "1.1.1-$0" # But it can also fail
}
```

My input file to be:

``` json
{ 
  "version": "{{ get_version_somehow beta }}"
} 
```

I don't want the final file to be even generated if the `get_version_somehow` fails.

**Comment by fidian** [comment]
Because you are using functions, I assume you are also sourcing `mo`. Might I suggest you put the version check before the call to process your template in your shell script?

```bash
VERSION=$(get_version_somehow beta) || {
    echo "Error getting version number." >&2
    exit 1
}

mo template.txt
```

**Comment by felipecassiors** [comment]
That does not become feasible when we have this function being called more than 10 times in a single template file, always with a different argument. And if this argument can not belong to the template file, it won't work for me (I don't want to leave the configuration on the scripts).
