### ISSUE TITLE
Deploy to npm for npm scripts

### ISSUE THREAD

**Issue by eirikb** [tests-always-included/mo#43]
Hi

It would be great to be able to use this as npm script. If it could automatically read from `.env` as well.
Making this possible: `npx @tests-always-included/mo somefile.mo somefile`

**Comment by fidian** [comment]
This is not a Node.js package and it appears that `npx` is strongly geared towards packages published in `npm`. Is there a way to inform `npx` or `npm` where this shell package lives without pretending that this is a Node module?

I'm against polluting the `npm` registry with this project because it is not written in JavaScript.

**Comment by eirikb** [comment]
Hi. I honestly thought this was written in JavaScript. I saw a `package.json`-file and some JavaScript files, but I see now they are only there for the tests. Sorry about that.
I agree it would polluting. There are a lot of on-the-edge packages in npm, some are even binary, but I agree in this case, as you don't even call out to node.
