### ISSUE TITLE
Seeking Feedback: Allow indirect values (Alternative to #58)

### ISSUE THREAD

**Issue by fidian** [tests-always-included/mo#62]
This proposal is an alternate to #58 to discuss a way to simply indirect a single value in order to add it as a base that we can build upon. Acceptance of this does not mean that #58 is resolved - both could be attacking different core problems. This also doesn't cover #61, even though there's important ideas in there that overlap and this should be compatible with being used in function arguments.

### Test Case

Keep in mind that the last line does not use correct syntax. This issue is to discuss a proposal to implement an extension to mustache to allow for indirect values.

```
x="test"
test="correct"

echo "{{!x}}" | ./mo
```

### Bash: `{{!x}}`

It would be nice if the above syntax would work because it mirrors how Bash will indirectly reference a variable. `echo "${!x}"` produces "correct". The above syntax will not work because `{{!` is already reserved as a comment in handlebars.

### C, Go: `{{*x}}`

C uses pointers and `*var` is how you dereference a pointer to get the target value. Go is similar.

### Makefile, PHP: `{{$$x}}` or `{{$x}}`

Makefiles and PHP use `$$var` syntax.

If we use `{{$$x}}`, there could be confusion because mustache doesn't require `$` in front of `{{x}}` for it to refer to the variable `$x`. If this one is selected, I would also recommend that `{{$x}}` works the same as `{{x}}`. Also, for #61, I would have `$x` pass the value of `$x` and `$$x` pass the indirect value of `$test` for consistency.

If we use `{{$x}}`, that could conflict with possible enhancements to function arguments in #61.
In there, `{{myfunc $var}}` could pass the value of `$var` to the function, which seems very intuitive and helps make sure old behavior is retained where everything was treated as a string.

### JavaScript: `{{[x]}}`

JavaScript sorta can do this with `window[x]`. I don't think I want to add more complexity to the parser. Finding closing tags to match braces is rough enough with what's going on. Having only a prefix would be ideal.

### BASIC: `{{#x}}`

Already taken by Mustache to iterate across `x`. Bash treats `#` as a comment. Doesn't fit well.

### Other Ideas

For the same reasons as what's listed for JavaScript, I would like to only have a prefix so the parser doesn't have to grow tremendously to find more closing tags.

For prefixes, there are a lot of other symbols that could be used. We must not use `_` because that can be a variable's name, and ideally it should be related to a common pattern.

**Comment by Swivelgames** [comment]
This proposal is an expanded version of #61, and I'm inclined to close #61 in favor of this, given that this can be made to include all use-cases, especially for consistency's sake. Which is great! I was going to effectively expand #61 in additional proposal to include the items you listed above.

The ideal solution would be able to work in all the scenarios so that (1) syntax is consistent, and (2) we don't stray too far away from what is known and comfortable among existing Mustache users. Straying too far away from Mustache can make it difficult to use existing Mustache templates with `mo`. Granted, we're already kind of there with things like function args and some other things. But I digress 😅

But if we could make it work with all scenarios, that would be superb:

- Direct Reference: `{{$x }}`
- Member Reference: `{{myvar.$x }}`
- Direct with Member Reference: `{{$x.key }}`
- Function Args: `{{#myfunc $x }}` `{{#myfunc $x.key }}` `{{#myfunc $x.$somekey }}`
- Throw in `@key` and `.` into this proposal, and you're done!


### ⚪ C, Go: `{{*x}}`

This works. Logic aside and personal opinions out front, it wouldn't be my first choice, but it's not terrible.

### 🟢 JavaScript: `{{[x]}}`

This isn't a bad idea, especially if it is expanded to array references. We already have dot-notation, and both JavaScript and Bash reference named-members the same: `obj[keyname]`.

- `{{myArr.x}}` will get `myArr[x]`
- `{{myArr[x]}}` will get `${myArr[$x]}`

However, non-array references aren't _as_ pretty. Not that it matters too much:

- `{{#myFunc [x] }}` calls `myFunc` with `"${$x}"`
- `{{[x]}}` will get `"${$x}"`

Dealing with the closing brace might not actually be as annoying as it seems, though. I might be able to throw something together to demonstrate what I mean.

### ⚪ Makefile: `{{$$x}}`

I'm not a _huge_ fan of this, simply because if #61 is closed in favor of this proposal, having the double `$` seems redundant. The next section kind of expands on why I would favor `$x` over `$$x`

### 🟢 PHP: `{{$x}}` _(and Bash, depending on your perspective)_

Honestly, this is probably my personal favorite; At minimum, it's a tie with JavaScript in my personal opinion.

The `$__` syntax is almost ubiquitous when used for interpolation, including in Bash itself (think `${assoc[$key]}`).

First of all, let's look at the current syntax that we have right now paired with this:

```bash
title="Foo Bar"
ref="title"

{{title}} # gives us "Foo Bar"
{{$ref}} # gives us "Foo Bar"
```

If we're thinking of it from the perspective of _interpolation_, which is effectively what this and #61 is, we're right on the money:

```c#
{{title}} => "title" => title => gets "Foo Bar"
{{$ref}} => "$ref" => title => gets "Foo Bar"
```

It feels a lot more natural. And, it can be used in all of the scenarios described:

- Direct Reference: `{{$ref }}`
- Member Reference: `{{myvar.$ref }}`
- Direct with Member Reference: `{{$ref.key }}`
- Function Args: `{{#myfunc $ref}}` `{{#myfunc $ref.key }}` `{{#myfunc $ref.$otherRef }}`
- Throw in `@key` and `$.` into this proposal, and you're done!


### 🟡 Bracket Notation over Dot Notation: A step towards interpolation? 

Another more involved proposal might be to enable `[]` notation for array/assoc references _in combination_ with the `$x` implementation:

- Direct Reference: `{{$ref }}`
- Member Reference: `{{myvar[$ref] }}`
- Direct with Member Reference: `{{$ref.key }}`
- Function Args: `{{#myfunc $ref}}` `{{#myfunc $ref.key }}` `{{#myfunc $ref[$otherRef] }}`

This combination, while slightly more involved, would be very intuitive to the user.

Especially when paired with `@key` and `.`:

```bash
x="test"
@key="foo"
.="bar"

{{data[$x]}} # Interpolated: data[test]
{{data[@key]}} # Interpolated: data[foo]
{{data[.]}} or {{data[$.]}} # Interpolated: data[bar]
{{data.x}} # Literal: data[x]
{{data.key}} # Literal: data[key]
```

**Comment by Swivelgames** [comment]
### Dot Notation

Totally see your point, and I agree completely. The closer to the Mustache spec we adhere, the better!

### Dot = current value

I was thinking about that whenever I implemented `@key` and `@index`. I think it would be a good idea, especially for these cases. `@value` doesn't exist in Mustache or Handlebars at the moment, but I see no reason why it wouldn't be an intuitive pattern to introduce.

# Backwards Compatibility

I would think that `{{myFunc one}}` would still turn into `myFunc "one"`, and `{{myFunc $one}}` would now become `myFunc "$one"`, especially if we're looking to maintain consistency as well as backwards compatibility. I wasn't aware that we were considering changing this portion, but I may be confused on that :sweat_smile: 

Granted, `{{myFunc one}}` interpolating to `myFunc "$one"` does appear to be consistent with Handlebars, so I'm not opposed to encouraging the use of quotes for arguments!

**Comment by fidian** [comment]
I think this is finally done. Also, while trying to get more of the non-standard mustache tests to pass, I stumbled across some interesting notation. It looks like `{{*var}}` will look up `$var`, insert its value, then look it up again. So if `var=abc` and `abc=works`, then `{{*var}}` results in "works" in the output. It's equivalent to `{{(var)}}` for me. I didn't implement that feature and the other stuff I noticed, but many more tests pass or have been analyzed and verified that they should not work with the Bash version of mustache.

Closing #62.
