### ISSUE TITLE
`!moResult: unbound variable` when sourced with an unset exported variable

### ISSUE THREAD

**Issue by Pinjasaur** [tests-always-included/mo#75]
Hey @fidian, thanks so much for this library.

Here's the scenario: when using `mo` _sourced_, if you `export` a variable and it has not been previously defined `mo` fails internally.

This took a while to get down to a lean reproducible example, but here we are:

```sh
#!/usr/bin/env bash

curl -sSL https://raw.githubusercontent.com/tests-always-included/mo/master/mo -o ./mo

export undefined_variable

# shellcheck disable=SC1091
source ./mo
echo "{{^undefined_variable}}Should render.{{/undefined_variable}}" | mo
```

Which errors with the following message:

```
./mo: line 1207: !moResult: unbound variable
```

Conversely, if you call `mo` directly it's not an issue. I'm almost always using `mo` with arrays, so it's unfortunately not much of a work around.

```sh
#!/usr/bin/env bash

curl -sSL https://raw.githubusercontent.com/tests-always-included/mo/master/mo -o ./mo
chmod +x ./mo

export undefined_variable
echo "{{^undefined_variable}}Should render.{{/undefined_variable}}" | ./mo
```

Yields, as expected:

```
Should render.
```

Let me know if you need any more information about my environment to reproduce it, but I've tested this on native macOS along with an Ubuntu LTS Docker container and both yielded the same result w/ Bash version 5.2.x.

**Comment by fidian** [comment]
Tricky problem. I put a bunch of comments in the commit, 7e86c1a. I guess exporting will define a variable and possibly set it internally to `null` or another value, but it's not really "set" since no value was ever assigned to it (including empty string). `mo` will treat this as not set and there's a test that now tests for this condition.

Thank you for not only reporting the problem, but also I tremendously appreciated the minimal reproduce case. That helped so much!
